### PR TITLE
Gain 100% coverage

### LINKED ISSUE #11: [test coverage] Reach 100% test coverage

### PR DESCRIPTION
**Pull request by jo**
- [ ] Close #11 when done
- [ ] update https://github.com/eHealthAfrica/kazana/issues/131 when done

### CODE REVIEW

**Comment by quesebifurcan** [comment]
Looks good to me. All tests pass.

**Comment by gr2m** [comment]
I see only 97% test coverage right now?

**Comment by jo** [comment]
Caching issue?

**Comment by jo** [comment]
Ah no. The coverage was not send to coveralls because it was implemented as a post semantic release hook and there were no release relevant changes

**Comment by jo** [comment]
https://travis-ci.org/eHealthAfrica/kazana-entities#L170

**Comment by gr2m** [comment]
Statements are 100%, but branches and functions are not

```
File                           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------|----------|----------|----------|----------|----------------|
All files                      |      100 |       90 |    94.74 |      100 |                |
```

**Comment by jo** [comment]
Didn't we agree on 100% lines coverage? Thats what makes the badges 100% green. Thats also what [shows up in the gh checks](https://github.com/eHealthAfrica/kazana-bootstrap/pull/33).

**Comment by jo** [comment]
Of course its better to have 100% branch and functions coverage. But for now I think 100% lines is enought. What do you mean @gr2m @quesebifurcan ?

**Comment by gr2m** [comment]
I usually try to get everything to 100%. Things like error handling of external libraries can be set to be ignored by istanbul, like here: https://github.com/eHealthAfrica/kazana-server/blob/master/index.js#L58-L61

**Comment by quesebifurcan** [comment]
@gr2m definitely has a point, why not go for 100% everywhere while we're at it?

**Comment by jo** [comment]
Apart from the numbers - which tests are missing here?

**Pull request merged**
